Repository apache/datafusion-ballista, pull requests merged in 2022-10, with the labels that each got.

#318 Update README in preparation for 0.9.0 release
  README.md
Labels: documentation

#367 Fix integration test and add more queries
  benchmarks/run.sh
  dev/integration-tests.sh
Labels: development-process

#366 Fixup links in README.md
  README.md
Labels: documentation

#413 MINOR: Delete unmaintained arm docker build
  dev/build-ballista-docker-arm64.sh
Labels: development-process

#128 Fix #127 Automatic version updates for github actions with dependabot
  .github/dependabot.yml
Labels: development-process

#431 Move scheduler UI files into scheduler module
  .github/workflows/typescript.yml
  ballista/scheduler/ui/.dockerignore
  ballista/scheduler/ui/.gitignore
  ballista/scheduler/ui/README.md
  ballista/scheduler/ui/index.d.ts
  ballista/scheduler/ui/package.json
  ballista/scheduler/ui/public/favicon.ico
  ballista/scheduler/ui/public/index.html
  ballista/scheduler/ui/public/logo192.png
  ballista/scheduler/ui/public/logo512.png
  ballista/scheduler/ui/public/manifest.json
  ballista/scheduler/ui/public/robots.txt
  ballista/scheduler/ui/react-table-config.d.ts
  ballista/scheduler/ui/src/App.css
  ballista/scheduler/ui/src/App.test.tsx
  ballista/scheduler/ui/src/App.tsx
  ballista/scheduler/ui/src/components/DataTable.tsx
  ballista/scheduler/ui/src/components/Empty.tsx
  ballista/scheduler/ui/src/components/ExecutorsList.tsx
  ballista/scheduler/ui/src/components/Footer.tsx
  ballista/scheduler/ui/src/components/Header.tsx
  ballista/scheduler/ui/src/components/JobStagesMetrics.tsx
  ballista/scheduler/ui/src/components/QueriesList.tsx
  ballista/scheduler/ui/src/components/Summary.tsx
  ballista/scheduler/ui/src/components/logo.svg
  ballista/scheduler/ui/src/index.css
  ballista/scheduler/ui/src/index.tsx
  ballista/scheduler/ui/src/react-app-env.d.ts
  ballista/scheduler/ui/src/reportWebVitals.ts
  ballista/scheduler/ui/src/setupTests.ts
  ballista/scheduler/ui/tsconfig.json
  ballista/scheduler/ui/yarn.lock
  dev/build-ui.sh
  dev/docker/ballista-scheduler.Dockerfile
  dev/docker/builder-entrypoint.sh
Labels: development-process

#432 0.9.0 Release
  ballista-cli/Cargo.toml
  ballista/CHANGELOG.md
  ballista/client/Cargo.toml
  ballista/core/Cargo.toml
  ballista/executor/Cargo.toml
  ballista/scheduler/Cargo.toml
  benchmarks/Cargo.toml
  dev/release/README.md
  dev/update_ballista_versions.py
  examples/Cargo.toml
  python/Cargo.toml
Labels: python, development-process

#433 README updates
  README.md
  docs/developer/images/ballista-benchmarks.png
Labels: documentation

#453 Bump DataFusion version
  ballista-cli/Cargo.toml
  ballista/client/Cargo.toml
  ballista/client/src/context.rs
  ballista/core/Cargo.toml
  ballista/core/proto/datafusion.proto
  ballista/core/src/execution_plans/distributed_query.rs
  ballista/core/src/serde/mod.rs
  ballista/core/src/serde/physical_plan/from_proto.rs
  ballista/core/src/serde/physical_plan/mod.rs
  ballista/core/src/utils.rs
  ballista/executor/Cargo.toml
  ballista/scheduler/Cargo.toml
  ballista/scheduler/src/display.rs
  ballista/scheduler/src/planner.rs
  ballista/scheduler/src/scheduler_server/event.rs
  ballista/scheduler/src/scheduler_server/mod.rs
  ballista/scheduler/src/state/execution_graph.rs
  ballista/scheduler/src/state/execution_graph_dot.rs
  ballista/scheduler/src/state/mod.rs
  benchmarks/Cargo.toml
  benchmarks/src/bin/tpch.rs
  examples/Cargo.toml
  python/Cargo.toml
  python/ballista/tests/test_catalog.py
  python/src/dataframe.rs
  python/src/dataset_exec.rs
  python/src/expression.rs
  python/src/functions.rs
  python/src/pyarrow_filter_expression.rs
Labels: python

#464 Support building docker images with release-lto
  dev/build-ballista-docker.sh
  dev/build-ballista-rust.sh
  dev/docker/builder-entrypoint.sh
  dev/release/README.md
Labels: development-process

#474 Check for expected benchmark results in integration test
  benchmarks/run.sh
  benchmarks/src/bin/tpch.rs
  benchmarks/tpch-gen.sh
  dev/integration-tests.sh
  dev/release/verify-release-candidate.sh
Labels: development-process

#471 Bump DataFusion
  ballista-cli/Cargo.toml
  ballista/client/Cargo.toml
  ballista/core/Cargo.toml
  ballista/core/proto/datafusion.proto
  ballista/core/src/serde/physical_plan/mod.rs
  ballista/executor/Cargo.toml
  ballista/scheduler/Cargo.toml
  benchmarks/Cargo.toml
  examples/Cargo.toml
  python/Cargo.toml
  python/src/dataframe.rs
Labels: python

#480 [Minor] Bump DataFusion
  ballista-cli/Cargo.toml
  ballista/client/Cargo.toml
  ballista/core/Cargo.toml
  ballista/core/proto/datafusion.proto
  ballista/core/src/serde/physical_plan/mod.rs
  ballista/executor/Cargo.toml
  ballista/scheduler/Cargo.toml
  benchmarks/Cargo.toml
  examples/Cargo.toml
  python/Cargo.toml
Labels: python
