Repository apache/datafusion-ballista, pull requests merged in 2023-02, with the labels that each got.

#647 Check in benchmark image
  README.md
  docs/sqlbench-h-workstation-10-distributed-perquery.png
Labels: documentation

#654 Remove `python` dir & python-related workflows
  .github/workflows/dev.yml
  .github/workflows/python_build.yml
  .github/workflows/python_test.yaml
  python/.cargo/config
  python/.dockerignore
  python/.gitignore
  python/CHANGELOG.md
  python/Cargo.toml
  python/LICENSE.txt
  python/README.md
  python/ballista/__init__.py
  python/ballista/functions.py
  python/ballista/tests/__init__.py
  python/ballista/tests/generic.py
  python/ballista/tests/test_aggregation.py
  python/ballista/tests/test_catalog.py
  python/ballista/tests/test_context.py
  python/ballista/tests/test_dataframe.py
  python/ballista/tests/test_functions.py
  python/ballista/tests/test_imports.py
  python/ballista/tests/test_sql.py
  python/ballista/tests/test_udaf.py
  python/pyproject.toml
  python/requirements-310.txt
  python/requirements-37.txt
  python/requirements.in
  python/requirements.txt
  python/src/ballista_context.rs
  python/src/catalog.rs
  python/src/context.rs
  python/src/dataframe.rs
  python/src/dataset.rs
  python/src/dataset_exec.rs
  python/src/datatype.rs
  python/src/errors.rs
  python/src/expression.rs
  python/src/functions.rs
  python/src/lib.rs
  python/src/pyarrow_filter_expression.rs
  python/src/udaf.rs
  python/src/udf.rs
  python/src/utils.rs
Labels: python

#682 Prep 0.11
  .github/workflows/rust.yml
  .gitignore
  ballista-cli/Cargo.toml
  ballista/CHANGELOG.md
  ballista/client/Cargo.toml
  ballista/core/Cargo.toml
  ballista/executor/Cargo.toml
  ballista/scheduler/Cargo.toml
  ballista/scheduler/ui/.gitignore
  ballista/scheduler/ui/yarn.lock
  benchmarks/Cargo.toml
  dev/update_ballista_versions.py
  examples/Cargo.toml
Labels: development-process
