Repository apache/datafusion-ballista, pull requests merged in 2023-01, with the labels that each got.

#596 MINOR: Fix benchmark image link
  README.md
Labels: documentation

#597 Remove outdated script and use evergreen version of rust
  .github/workflows/rust.yml
  dev/build-ballista-docker.sh
  dev/build-ballista-executables.sh
  dev/build-ui.sh
  dev/docker/ballista-builder.Dockerfile
Labels: development-process

#621 Rename default branch from master to main
  .github/dependabot.yml
  .github/workflows/comment_bot.yml
  dev/release/README.md
  dev/release/create-tarball.sh
  dev/release/update_change_log-ballista.sh
  dev/release/update_change_log.sh
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user-guide/deployment/docker-compose.md
Labels: development-process

#639 Upgrade to DataFusion 17
  ballista-cli/Cargo.toml
  ballista/client/Cargo.toml
  ballista/core/Cargo.toml
  ballista/core/src/client.rs
  ballista/core/src/serde/generated/ballista.rs
  ballista/core/src/serde/mod.rs
  ballista/executor/Cargo.toml
  ballista/executor/src/flight_service.rs
  ballista/scheduler/Cargo.toml
  ballista/scheduler/src/flight_sql.rs
  benchmarks/Cargo.toml
  benchmarks/src/bin/tpch.rs
  examples/Cargo.toml
  python/Cargo.toml
Labels: python
